ci: implement pr releases

diff --git a/.github/workflows/release-app.yml b/.github/workflows/release-app.yml
--- a/.github/workflows/release-app.yml
+++ b/.github/workflows/release-app.yml
@@ -1,87 +1,90 @@
 name: Release App
 
 on:
-  workflow_dispatch:
+  workflow_call:
     inputs:
       app:
-        type: choice
-        description: Which app to release
-        options:
-          - api
-          - deploy-web
+        description: 'The app to release'
         required: true
-      release-type:
-        type: choice
-        description: Which app to release
-        options:
-          - prod
-          - beta
-        default: prod
-      force-build:
-        type: boolean
-        description: Rebuild the Docker image
-        default: false
+        type: string
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
+  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.app }}
   cancel-in-progress: true
+
+permissions:
+  contents: write
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0
+          fetch-depth: 2
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.14.0
+      - name: Get Diffs
+        id: bumps
+        run: |
+          # File paths
+          changelog_file="apps/${{ inputs.app }}/CHANGELOG.md"
+          package_file="apps/${{ inputs.app }}/package.json"
 
-      - name: Restore root node_modules cache
-        uses: actions/cache@v4
-        id: cache
-        with:
-          path: |
-            node_modules
-            apps/${{ github.event.inputs.app }}/node_modules
-            packages/*/node_modules
-          key: ${{ github.event.inputs.app }}-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
+          # Check if the files exist
+          if [ ! -f "$changelog_file" ]; then
+            echo "Error: Changelog file $changelog_file does not exist."
+            exit 1
+          fi
 
-      - name: Install dependencies
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: npm ci
+          if [ ! -f "$package_file" ]; then
+            echo "Error: Package file $package_file does not exist."
+            exit 1
+          fi
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          # Determine the merge base
+          merge_base=$(git merge-base HEAD^ HEAD)
+          if [ -z "$merge_base" ]; then
+            echo "Error: Could not determine merge base."
+            exit 1
+          fi
 
-      - name: Build the Docker images
+          # Get changelog content changes (only added lines without metadata)
+          changelog_diff=$(git diff $merge_base HEAD -- "$changelog_file" | grep -E '^\+' | grep -vE '^\+\+\+|^diff|^index|^@@' | sed 's/^+//')
+
+          if [ -n "$changelog_diff" ]; then
+            echo "changelog<<EOF" >> $GITHUB_OUTPUT
+            echo "$changelog_diff" >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+          fi
+
+          # Get version diff
+          current_version=$(jq -r '.version' "$package_file")
+          previous_version=$(git show $merge_base:"$package_file" | jq -r '.version' || echo "Not found")
+
+          if [ "$previous_version" != "Not found" ] && [ "$current_version" != "$previous_version" ]; then
+            echo "version=$current_version" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Echo the version and changelog
+        run: |
+          echo "---- version start ----"
+          echo "${{ steps.bumps.outputs.version }}"
+          echo "---- version end ----"
+          echo "---- changelog start ----"
+          echo "${{ steps.bumps.outputs.changelog }}"
+          echo "---- changelog end ----"
+
+      - name: Create Release
+        if: ${{ steps.bumps.outputs.version != '' }}
+        id: create_release
+        uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          git config --global user.email "ci@akash.network"
-          git config --global user.name "CI"
-          
-          pre_release=""
-          if [[ "${{ github.event.inputs.release-type }}" == 'beta' ]]; then
-            prerelease="--preRelease=beta"
-          fi
-          
-          force_build=""
-          if [[ "${{ github.event.inputs.force-build }}" == 'true' ]]; then
-              force_build="-f"
-          fi
-          
-          repo="${{ github.event.inputs.app == 'api' && vars.API_REGISTRY || vars.WEB_REGISTRY }}"
-          
-          npm run release -w apps/${{ github.event.inputs.app }} -- $pre_release $force_build --verbose --ci -r $repo
+        with:
+          tag_name: ${{ inputs.app }}/${{ steps.bumps.outputs.version }}
+          release_name: Release ${{ inputs.app }}/${{ steps.bumps.outputs.version }}
+          body: |
+            ${{ steps.bumps.outputs.changelog }}
+          prerelease: true
